server:
  port: 8083

spring:
  application:
    name: ique-qms
  cloud:
    gcp:
      sql:
        enable: true
        database-name: qms
        instance-connection-name: ique-star6ucks:asia-southeast1:queue-db
      project-id: ique-star6ucks
      credentials:
        location: file:_key.json
  datasource:
    username: queue-manager
    password: rTJBMdkj6LrCSf0+